// data/posts.js
export const dummyPosts = [
  {
    id: 1,
    userName: "Emily Rodriguez",
    userTitle: "Marketing Director at GlobalBrands",
    userImage: "https://randomuser.me/api/portraits/women/10.jpg",
    timeAgo: "2h ago",
    content:
      "Excited to announce our latest marketing campaign that increased user engagement by 45%! Check out the case study on our website. #Marketing #DigitalStrategy",
    image: null,
    likes: 36,
    likedBy: ["John Doe", "Sarah Wong", "34 others"],
    comments: 5,
    isLiked: false,
    commentsList: [
      {
        id: 101,
        user: "John Doe",
        userImage: "https://randomuser.me/api/portraits/men/5.jpg",
        text: "Impressive results! Would love to hear more about your approach.",
        timestamp: "1h ago",
        likes: 3,
        isLiked: false,
        replies: [],
      },
      {
        id: 102,
        user: "Sarah Clark",
        userImage: "https://randomuser.me/api/portraits/women/7.jpg",
        text: "Congratulations on the success! Our team is looking for similar strategies.",
        timestamp: "2h ago",
        likes: 5,
        isLiked: false,
        replies: [
          {
            id: 201,
            user: "Emily Rodriguez",
            userImage: "https://randomuser.me/api/portraits/women/10.jpg",
            text: "Thank you! I'd be happy to connect and share some insights.",
            timestamp: "1h ago",
            likes: 2,
            isLiked: false,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    userName: "David Kim",
    userTitle: "Software Engineer at TechCorp",
    userImage: "https://randomuser.me/api/portraits/men/20.jpg",
    timeAgo: "4h ago",
    content:
      "Just finished an amazing project using React Native and TypeScript. The performance improvements were incredible! #ReactNative #MobileDev",
    image: null,
    likes: 48,
    likedBy: ["Alex Johnson", "Maria Wong", "46 others"],
    comments: 10,
    isLiked: false,
    commentsList: [
      {
        id: 201,
        user: "Alex Johnson",
        userImage: "https://randomuser.me/api/portraits/men/15.jpg",
        text: "Would you mind sharing what specific optimizations you made?",
        timestamp: "2h ago",
        likes: 4,
        isLiked: false,
        replies: [
          {
            id: 301,
            user: "David Kim",
            userImage: "https://randomuser.me/api/portraits/men/20.jpg",
            text: "Sure! I implemented virtualized lists and memoization for complex components. I'll share a blog post about it soon.",
            timestamp: "1h ago",
            likes: 2,
            isLiked: false,
          },
        ],
      },
      {
        id: 202,
        user: "Maria Wong",
        userImage: "https://randomuser.me/api/portraits/women/22.jpg",
        text: "Awesome! I've been working with React Native too. Let's connect!",
        timestamp: "3h ago",
        likes: 1,
        isLiked: false,
        replies: [],
      },
    ],
  },
  {
    id: 3,
    userName: "Sarah Johnson",
    userTitle: "UX Designer at CreativeLabs",
    userImage: "https://randomuser.me/api/portraits/women/30.jpg",
    timeAgo: "1d ago",
    content:
      "Had a great time at the design thinking workshop yesterday. So many innovative ideas from talented alumni! Looking forward to implementing some of these concepts in our next project.",
    image:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80",
    likes: 72,
    likedBy: ["Michael Chen", "Lisa Park", "70 others"],
    comments: 15,
    isLiked: false,
    commentsList: [
      {
        id: 301,
        user: "Michael Chen",
        userImage: "https://randomuser.me/api/portraits/men/25.jpg",
        text: "The workshop was fantastic! I particularly enjoyed the brainstorming session.",
        timestamp: "22h ago",
        likes: 6,
        isLiked: false,
        replies: [],
      },
      {
        id: 302,
        user: "Lisa Park",
        userImage: "https://randomuser.me/api/portraits/women/27.jpg",
        text: "Great seeing you there! Let's connect to discuss some of those ideas.",
        timestamp: "23h ago",
        likes: 3,
        isLiked: false,
        replies: [
          {
            id: 401,
            user: "Sarah Johnson",
            userImage: "https://randomuser.me/api/portraits/women/30.jpg",
            text: "Definitely! I'll send you a message to schedule something.",
            timestamp: "20h ago",
            likes: 1,
            isLiked: false,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    userName: "James Wilson",
    userTitle: "Product Manager at InnovateTech",
    userImage: "https://randomuser.me/api/portraits/men/35.jpg",
    timeAgo: "1d ago",
    content:
      "Proud to announce that our team has just shipped v2.0 of our app with a completely redesigned UI and improved user flows. Thanks to everyone who contributed! #ProductDevelopment #UX",
    image:
      "https://images.unsplash.com/photo-1556155092-490a1ba16284?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    likes: 95,
    likedBy: ["Emma Davis", "Ryan Smith", "93 others"],
    comments: 24,
    isLiked: false,
    commentsList: [
      {
        id: 401,
        user: "Emma Davis",
        userImage: "https://randomuser.me/api/portraits/women/35.jpg",
        text: "The new design is amazing! So much easier to navigate now.",
        timestamp: "20h ago",
        likes: 7,
        isLiked: false,
        replies: [],
      },
      {
        id: 402,
        user: "Ryan Smith",
        userImage: "https://randomuser.me/api/portraits/men/40.jpg",
        text: "Great work team! The performance improvements are noticeable too.",
        timestamp: "21h ago",
        likes: 5,
        isLiked: false,
        replies: [
          {
            id: 501,
            user: "James Wilson",
            userImage: "https://randomuser.me/api/portraits/men/35.jpg",
            text: "Thanks Ryan! We spent a lot of time optimizing load times.",
            timestamp: "19h ago",
            likes: 2,
            isLiked: false,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    userName: "Jennifer Lopez",
    userTitle: "Data Scientist at AnalyticsPro",
    userImage: "https://randomuser.me/api/portraits/women/42.jpg",
    timeAgo: "2d ago",
    content:
      "Just published my research on predictive models for customer behavior. We achieved 87% accuracy using a hybrid approach combining traditional ML with neural networks. #DataScience #MachineLearning",
    image: null,
    likes: 128,
    likedBy: ["Thomas Wright", "Samantha Lee", "126 others"],
    comments: 32,
    isLiked: false,
    commentsList: [
      {
        id: 501,
        user: "Thomas Wright",
        userImage: "https://randomuser.me/api/portraits/men/45.jpg",
        text: "This is groundbreaking work! Would love to chat about how you handled the feature selection process.",
        timestamp: "1d ago",
        likes: 12,
        isLiked: false,
        replies: [
          {
            id: 601,
            user: "Jennifer Lopez",
            userImage: "https://randomuser.me/api/portraits/women/42.jpg",
            text: "Happy to discuss! We used a combination of PCA and domain expertise. I'll DM you more details.",
            timestamp: "1d ago",
            likes: 3,
            isLiked: false,
          },
        ],
      },
      {
        id: 502,
        user: "Samantha Lee",
        userImage: "https://randomuser.me/api/portraits/women/45.jpg",
        text: "I'm implementing something similar for my company. Is the paper available online?",
        timestamp: "2d ago",
        likes: 8,
        isLiked: false,
        replies: [],
      },
    ],
  },
  {
    id: 6,
    userName: "Robert Chen",
    userTitle: "Frontend Developer at WebSolutions",
    userImage: "https://randomuser.me/api/portraits/men/52.jpg",
    timeAgo: "3d ago",
    content:
      "Just released my new open-source library for animation transitions in React. Check it out on GitHub and let me know what you think! #OpenSource #ReactJS #WebDevelopment",
    image:
      "https://images.unsplash.com/photo-1581276879432-15e50529f34b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    likes: 83,
    likedBy: ["Karen Taylor", "Miguel Sanchez", "81 others"],
    comments: 19,
    isLiked: false,
    commentsList: [
      {
        id: 601,
        user: "Karen Taylor",
        userImage: "https://randomuser.me/api/portraits/women/52.jpg",
        text: "This is exactly what I've been looking for! The demos look amazing.",
        timestamp: "2d ago",
        likes: 5,
        isLiked: false,
        replies: [],
      },
      {
        id: 602,
        user: "Miguel Sanchez",
        userImage: "https://randomuser.me/api/portraits/men/55.jpg",
        text: "Already implemented it in my project and it works flawlessly. Great documentation too!",
        timestamp: "3d ago",
        likes: 7,
        isLiked: false,
        replies: [
          {
            id: 701,
            user: "Robert Chen",
            userImage: "https://randomuser.me/api/portraits/men/52.jpg",
            text: "So glad to hear that! If you have any feature requests, please submit an issue on GitHub.",
            timestamp: "2d ago",
            likes: 2,
            isLiked: false,
          },
        ],
      },
    ],
  },
];
